import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
// import { AppController } from './app.controller';
// import { AppService } from './app.service';
import { UsersModule } from './users/users.module';
import { ClipboardModule } from './clipboard/clipboard.module';
import { DevicesModule } from './devices/devices.module';

import { appconfig } from './utils/config';
import { LoggerOptions } from 'typeorm';
import { ClipgroupModule } from './clipgroup/clipgroup.module';

@Module({
  imports: [
    UsersModule,
     TypeOrmModule.forRoot({ //TODO: move the whole config to a separate file and import here
      type: appconfig.db.dbtype as any, // or mysql, sqlite, etc.
      host: appconfig.db.host, 
      port: appconfig.db.port,
      username: appconfig.db.username, //TODO: Move to env variable
      password: appconfig.db.password, //TODO: Move to env variable
      database: appconfig.db.database, //TODO: Move to env variable
      autoLoadEntities: true, // IMPORTANT: This loads entities generated by CLI
      synchronize: true, 
      logging: appconfig.db.logging as LoggerOptions,
     // Set to false in production!
    }),
     ClipboardModule,
     DevicesModule,
     ClipgroupModule,
    ],
  // controllers: [AppController],
  // providers: [AppService],
})
export class AppModule {}
