import { Entity } from "typeorm";
import { Column, PrimaryGeneratedColumn, ManyToOne, JoinColumn, CreateDateColumn, Index, BeforeInsert } from 'typeorm';
import { User } from "../../users/entities/user/user";
import { Exclude, Expose } from 'class-transformer';
import * as crypto from 'crypto';
import { IsOptional, IsString } from "class-validator";

export enum ipType {
    IPv4 = 'IPv4',
    IPv6 = 'IPv6'
}

@Entity('devices')
@Index(['isActive'])
// @Index(['apiKey'])
export class Device {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // @IsOptional()
  // @Column({ type: 'uuid', default: null})
  // userId: string;

  @IsOptional()
  @ManyToOne(() => User, user => user.devices, { onDelete: 'CASCADE' })
  user: User;

  @Column({ unique: true })
  deviceFingerprint: string; // Generated by daemon

  @Column()
  name: string; // e.g., "MacBook Pro", "Windows Desktop"


  @Exclude()
  @Expose({ groups: ['device:create'] })
  @Column({ unique: true })
  apiKey: string; // Used by daemon for API requests

  //should be a json column with metadata about the platform(client)
  @IsOptional()
  @Column({ type: 'jsonb', nullable: true })
  platformInfo: Record<string, any>;

  @Column({ default: true })
  isActive: boolean;

  @Column({ type: 'timestamp', nullable: true })
  lastSeen: Date;

  @CreateDateColumn()
  createdAt: Date;

  @Column({ default: false })
  isPrimary: boolean;

  @BeforeInsert()
  generateApiKey() {
    if (!this.apiKey) {
      this.apiKey = `clipsynk_${crypto.randomBytes(32).toString('hex')}`;
    }
  }

  updateLastSeen() {
    this.lastSeen = new Date();
  }

  promoteToPrimary() {
    this.isPrimary = true;
  }

}